#!/bin/bash

cd /home/username/nasa

curl https://apod.nasa.gov/apod.rss | grep -E "http.*\.html" | sed "s/.*\(http.*\.html\).*/\1/" | xargs curl | grep -o '<a href="[^"]*' | grep -o '[^"]*.jpg$' | awk '{print "https:\/\/apod.nasa.gov\/apod\/"$1}' | xargs wget -N

